### ISSUE TITLE
Silverstripe 5 support

### ISSUE THREAD

**Issue by axllent** [bummzack/silverstripe-emogrify#5]
Hi there @bummzack  (CC @SiteTools). I am wondering if you have plans to support Silverstripe 5 with symfony/mailer, including PHP 8.[12], or should we be looking for an alternative option for emogrify & Silverstripe?  Thanks!

**Comment by bummzack** [comment]
Hi @axllent . Good question. I didn't have the time to work with SilverStripe 5 yet, but since the Email API changed from Swiftmailer to Symfony, this won't be as easy as updating the composer requirements 😀 

Apparently, there's already another package out there, probably based on this one? https://github.com/innowebau/silverstripe-symfony-mailer-emogrifier

Not sure if it's worth having two packages for the same feature, so I guess I'd mark this package as deprecated/abandoned in due time 🤷

**Comment by axllent** [comment]
That's cool, I just thought I'd check before switching modules. Yours has been part of a default set of useful modules I've used in the past for several projects, so I thought I would ask first. I don't like changing modules for the sake of it 😄
